### ISSUE TITLE
Jenkins Pipeline script edit page

### ISSUE THREAD

**Issue by s1mple-child** [jenkinsci/dark-theme-plugin#127]
Hi, Developer:

 I found dark theme for Jenkins from the blog posted on Jenkins official blog page. And used for a while, I think it's awesome.Thanks for your fantastic job. 👍 

 I found one place.When I created a pipeline job and used **Pipeline script** option not  **Pipeline script from SCM** and develop my pipeline script, I found the pipeline script edit page color is still white. If this page color as same as Jenkins main page theme, I think it will looks more coordinate.

 This is my suggestion.Thanks for your feedback. ❤️

**Comment by timja** [comment]
Hi thanks for the feedback.

I’ve looked at fixing this previously.
I’m just not sure the best way to do it,

I think it needs an extension point in the pipeline plugin that provides this.

That would be quite straightforward for plain dark theme, but I don’t know how to handle supporting the OS respecting setting. We may need to fork the dark theme for the editor and add our own which includes the required css which probably is the most straightforward approach

**Comment by 0N0thing** [comment]
> Hi thanks for the feedback.
> 
> I’ve looked at fixing this previously.
> I’m just not sure the best way to do it,
> 
> I think it needs an extension point in the pipeline plugin that provides this.
> 
> That would be quite straightforward for plain dark theme, but I don’t know how to handle supporting the OS respecting setting. We may need to fork the dark theme for the editor and add our own which includes the required css which probably is the most straightforward approach

Yeah, you are right.I almost forget this plain is provided by Jenkins pipeline: Groovy plugin. 

Because I'm a  Windows user, so I can't sonsider much of OS problem. As a developer it's necessary to consider this. But it's an optional job I think. If some more important jobs in your todo list, I think you can put this in the future. Maybe someday the plugin provide dark theme. 😆  

Also thanks for your feedback. Looking forward to your next update version. ❤️
